-- Base de datos raiz en modo de escritura

ALTER SESSION SET CONTAINER=CDB$ROOT;

ALTER DATABASE OPEN;


-- Base de datos XEPDB1 en modo read-only

ALTER PLUGGABLE DATABSE XEPDB1 OPEN READ ONLY;


-- Creacion de la PDB2
CREATE PLUGGABLE DATABSE XEPDB2 FROM XEPDB1;


-- Abrir la nueva PDB

ALTER PLUGGABLE DATABASE XEPDB2 OPEN;


-- Volver abrir en modo de escritura a la PDB1

ALTER PLUGGABLE DATABASE XEPDB1 CLOSE;
ALTER PLUGGABLE DATABASE XEPDB1 OPEN;


-- Verificación del usuario en la XEPDB2

ALTER SESSION SER CONTAINER=XEPDB2;

CREATE USER dkuser IDENTIFIED BY dkpassword;

GRANT CONNECT, RESOURCE TO dkuser;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE to dkuser;

ALTER USER  dkuser QUOTA UNLIMITED ON users;
