--  DK-Intermedio

-- verificación de entorno
SELECT SYS_CONTEXT('USERENV', 'CON_NAME') AS CURRENT_CONTAINER FROM DUAL;

-- Cambiarse a la PDB

ALTER SESSION SET CONTAINER = XEPDB1;

SELECT NAME, CON_ID, CON_NAME FROM V$CONTAINERS;


-- Creación de ususario

CREATE USER dkuser IDENTIFIED BY dkpassword
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

-- Permisos

GRANT CONNECT, RESOURCE TO dkuser;
ALTER USER dkuser QUOTA UNLIMITED ON users;


-- Espacio ilimitado en el tablespace users.

ALTER USER dkuser QUOTA UNLIMITED ON users;


-- Verificar la configuración

CONN dkuser/dkpassword@dkdatabase

CREATE TABLE test_table (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100)
);

INSERT INTO test_table (name) VALUES ('Prueba');

SELECT * FROM test_table;


-- Verificar el nombre del servicio
SELECT NAME FROM V$SERVICES;
