-- Cambiamos de sesión
ALTER SESSION SET CONTAINER = XEPDB1;

-- Crear un esquema y asignar permisos
CREATE USER dkuser IDENTIFIED BY dkpassword;
GRANT CONNECT, RESOURCE TO dkuser;

-- Espacio ilimitado en el tablespace users
ALTER USER dkuser QUOTA UNLIMITED ON users;

-- Crear una tabla en el esquema
CREATE TABLE dkuser.productos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(30),
    price NUMBER
);

-- Insertar datos iniciales
INSERT INTO dkuser.productos (name, price) VALUES ('Product A', 200);
INSERT INTO dkuser.productos (name, price) VALUES ('Product B', 300);

-- Confirmamos las inserciones
COMMIT;