version: "3.9"
services:
  dki-oracle-db:
    container_name: dki-oracle-container   
    image: container-registry.oracle.com/database/express:21.3.0-xe   
    environment:
      ORACLE_PWD: Netec_123 
      ORACLE_SID: XE
      ORACLE_PDB: XEPDB1
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1521:1521"  
      - "5500:5500"   
    volumes:
      - dki-oracle-data:/opt/oracle/oradata   
      - ./scripts:/opt/oracle/scripts/startup  # Montar el directorio de scripts
    networks:
      - dki-network   
volumes:
  dki-oracle-data:   
networks:
  dki-network: 
     driver: bridge