apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-productos
  labels:
    app: ms-productos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-productos
  template:
    metadata:
      labels:
        app: ms-productos
    spec:
      containers:
        - name: ms-productos
          image: TU-IMAGEN-AQUI
          args:
            - "--spring.config.additional-location=file:/config/"
          ports:
            - containerPort: 9081

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9081
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9081
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3

          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

          resources:
            requests:
              cpu: "400m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "800Mi"

          volumeMounts:
            - name: config-volume
              mountPath: /config/application.yml
              subPath: application.yml

      volumes:
        - name: config-volume
          configMap:
            name: ms-productos-config
            items:
              - key: application.yml
                path: application.yml