-- Cambiamos de sesión a la PDB
ALTER SESSION SET CONTAINER = XEPDB1;

-- Crear el usuario y asignar permisos
CREATE USER dkuser IDENTIFIED BY dkpassword;
GRANT CONNECT, RESOURCE TO dkuser;

-- Establecer el espacio ilimitado en el tablespace users.
ALTER USER dkuser QUOTA UNLIMITED ON users;

drop TABLE dkuser.productos;
-- Crear una tabla en el esquema
CREATE TABLE dkuser.productos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(30),
    descripcion VARCHAR2(50),
    precio NUMBER,
    stock NUMBER
);

-- Insertar datos iniciales
INSERT INTO dkuser.productos (nombre, descripcion, precio, stock) VALUES ('Product A','Product A', 200,1100);
INSERT INTO dkuser.productos (nombre, descripcion, precio, stock) VALUES ('Product B','Product B', 300,3100);

-- Confirmamos las inserciones
COMMIT;